<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="prgRWEffIO_1" Id="{2c14cec2-aa67-4d70-9f7f-7705637a4e16}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM prgRWEffIO_1
VAR
	fbRW1		: FB_ReadWrite_V2;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbRW1(eUploadType := eSelectDataUploadType.e_Change_Intervall5min, bBusy=> , bError=> , udiErrorCodeOut=> , eErrorReadWrite_Out=> );]]></ST>
    </Implementation>
    <LineIds Name="prgRWEffIO_1">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>