<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="prgRWEffIO_H1" Id="{02288258-8b1d-4dbd-8ad3-1a1bf94c5849}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM prgRWEffIO_H1
VAR
	fbRW1		: FB_ReadWrite_V2;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbRW1(	eUploadType := eSelectDataUploadType.e_Change_Intervall5min,
		bBusy=> , 
		bError=> , 
		udiErrorCodeOut=> , 
		eErrorReadWrite_Out=> );]]></ST>
    </Implementation>
    <LineIds Name="prgRWEffIO_H1">
      <LineId Id="10" Count="3" />
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>