<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="prgAD" Id="{712d74d9-10b1-407b-af8d-a8bbec12358b}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM prgAD
VAR
	int_HeartBeat					: INT;										//{#lynus.ag#()}
	byte_ErrorWarning				: BYTE;										//{#lynus.ag#()}
	m_HistoryAnomalyDetectionReady	: BOOL;										//{#lynus.ag#()}
	byte_AnomalySore				: BYTE;										//{#lynus.ag#()}
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="prgAD">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>