<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="prgUv12a" Id="{2cc0731d-e94b-4368-91c8-d0b2faf8cae4}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM prgUv12a
// Unterverteiler 12A
VAR
{region "Daten"}
  MessungA_ActivePower      AT %I* : REAL; //{#lynus.ag#()}
  MessungA_L1_Voltage       AT %I* : REAL; //{#lynus.ag#()}
  MessungA_L1_Current       AT %I* : REAL; //{#lynus.ag#()}
  MessungA_L1_PowerActive   AT %I* : REAL; //{#lynus.ag#()}
  MessungA_L1_PowerApparent AT %I* : REAL; //{#lynus.ag#()}
  MessungA_L1_PowerReactive AT %I* : REAL; //{#lynus.ag#()}
  MessungA_L1_PowerFactor   AT %I* : REAL; //{#lynus.ag#()}
  MessungA_L2_Voltage       AT %I* : REAL; //{#lynus.ag#()}
  MessungA_L2_Current       AT %I* : REAL; //{#lynus.ag#()}
  MessungA_L2_PowerActive   AT %I* : REAL; //{#lynus.ag#()}
  MessungA_L2_PowerApparent AT %I* : REAL; //{#lynus.ag#()}
  MessungA_L2_PowerReactive AT %I* : REAL; //{#lynus.ag#()}
  MessungA_L2_PowerFactor   AT %I* : REAL; //{#lynus.ag#()}
  MessungA_L3_Voltage       AT %I* : REAL; //{#lynus.ag#()}
  MessungA_L3_Current       AT %I* : REAL; //{#lynus.ag#()}
  MessungA_L3_PowerActive   AT %I* : REAL; //{#lynus.ag#()}
  MessungA_L3_PowerApparent AT %I* : REAL; //{#lynus.ag#()}
  MessungA_L3_PowerReactive AT %I* : REAL; //{#lynus.ag#()}
  MessungA_L3_PowerFactor   AT %I* : REAL; //{#lynus.ag#()}

  MessungB_I1_Current       AT %I* : REAL; //{#lynus.ag#()}
  MessungB_I2_Current       AT %I* : REAL; //{#lynus.ag#()}
  MessungB_I3_Current       AT %I* : REAL; //{#lynus.ag#()}
  MessungB_I4_Current       AT %I* : REAL; //{#lynus.ag#()}
  MessungB_I5_Current       AT %I* : REAL; //{#lynus.ag#()}
  MessungB_I6_Current       AT %I* : REAL; //{#lynus.ag#()}

  MessungC_I1_Current       AT %I* : REAL; //{#lynus.ag#()}
  MessungC_I2_Current       AT %I* : REAL; //{#lynus.ag#()}
  MessungC_I3_Current       AT %I* : REAL; //{#lynus.ag#()}
  MessungC_I4_Current       AT %I* : REAL; //{#lynus.ag#()}
  MessungC_I5_Current       AT %I* : REAL; //{#lynus.ag#()}
  MessungC_I6_Current       AT %I* : REAL; //{#lynus.ag#()}

  MessungD_I1_Current       AT %I* : REAL; //{#lynus.ag#()}
  MessungD_I2_Current       AT %I* : REAL; //{#lynus.ag#()}
  MessungD_I3_Current       AT %I* : REAL; //{#lynus.ag#()}
  MessungD_I4_Current       AT %I* : REAL; //{#lynus.ag#()}
  MessungD_I5_Current       AT %I* : REAL; //{#lynus.ag#()}
  MessungD_I6_Current       AT %I* : REAL; //{#lynus.ag#()}
{endregion}

{region "IO"}
{endregion}
END_VAR

]]></Declaration>
    <Implementation>
      <ST><![CDATA[
;
]]></ST>
    </Implementation>
    <LineIds Name="prgUv12a">
      <LineId Id="248" Count="1" />
      <LineId Id="17" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>