{
 "title": "MPC event driven architecture monitoring (provisioned)",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "DS_LOKI", "label": "loki datasource", "query": "loki" },
   {
    "name": "rabbitmq_cluster",
    "label": "RabbitMQ Cluster",
    "query": {
     "query": "label_values(rabbitmq_identity_info{namespace=\"$namespace\"},rabbitmq_cluster)"
    }
   },
   { "name": "namespace", "label": "Namespace" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Waiting messages",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_ready * on(instance, job) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running jobs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mpc_running_jobs_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Message without ack",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_unacked * on(instance, job) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# published training (5m)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"mpc\"} |= `Publish to 'task_queue'` |= `train`[5m]))"
    }
   ]
  },
  {
   "title": "# published predictions log occurences (5m)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"mpc\"} |= `Publish to 'task_queue'` |= `prediction`[5m]))"
    }
   ]
  },
  {
   "title": "Scaler Target (# of pods)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 6 },
   "targets": [
    {
     "expr": "keda_scaler_metrics_value{scaler=\"composite-metric\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Holders in list log occurences (5m)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"mpc\"} |= `holder already in list` [5m]))"
    }
   ]
  },
  {
   "title": "Models skipped scheduling",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count by(uuid) (rate({app=\"mpc\"} | regexp `(?P<uuid>[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}) for holder already in list` | line_format `{{.uuid}}` | uuid != `` [$__interval]))"
    }
   ]
  },
  { "title": "Job durations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "EMS Prediction Duration (avg 95% quantile)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(mpc_ems_prediction_bucket[$__rate_interval])))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "SPO Prediction Duration (avg 95% quantile)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(mpc_setpoint_optimizer_prediction_bucket[$__rate_interval])))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Loadmonitor Prediction Duration (avg 95% quantile)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(mpc_load_monitor_prediction_bucket[$__rate_interval])))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Consumption Prediction Duration (avg 95% quantile)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(mpc_consumption_service_prediction_bucket[$__rate_interval])))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "History Anomaly Prediction Duration (avg 95% quantile)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(mpc_history_anomaly_detection_prediction_bucket[$__rate_interval])))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Stream Anomaly Prediction Duration (avg 95% quantile)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(mpc_stream_anomaly_detection_prediction_bucket[$__rate_interval])))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "PV Production Prediction Duration (avg 95% quantile)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(mpc_pv_production_service_prediction_bucket[$__rate_interval])))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "PV Monitoring Prediction Duration (avg 95% quantile)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(mpc_pv_monitoring_service_prediction_bucket[$__rate_interval])))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Train Model (once?) Duration (avg 95% quantile)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(mpc_train_model_thread_bucket[$__rate_interval])))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Train Model daily Duration (avg 95% quantile)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(mpc_train_model_daily_bucket[$__rate_interval])))",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}