{
 "title": "Alerts",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "LOG alert",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{namespace=~\"longhorn-system|kube-system|lynus\"} |~ `err|warn|deprecated|experimental`"
    }
   ]
  },
  {
   "title": "actual RAM usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "(1- (node_memory_MemAvailable_bytes{} / node_memory_MemTotal_bytes{})) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU alert",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m]) * 100) * on(instance) group_left(nodename) (node_uname_info))"
    }
   ]
  },
  {
   "title": "HDD alert",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "RAM alert",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{} - node_memory_MemFree_bytes{}) / (node_memory_MemTotal_bytes{} )) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}