{
 "title": "EfficientIO API",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "API & MQTT Proxy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "API requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(api_requests_total{realm=~\".+\"}[$__rate_interval])",
     "legendFormat": "{{realm}}"
    }
   ]
  },
  {
   "title": "MQTT Authorizations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "increase(proxy_connections_total{status=~\".+\"}[$__rate_interval])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Messages",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(recorder_measurements_total[$__range])",
     "legendFormat": "Messages"
    }
   ]
  },
  {
   "title": "Messages/s",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(recorder_measurements_total[1m])",
     "legendFormat": "messages/s"
    }
   ]
  },
  {
   "title": "Clients connected",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "broker_clients_connected" }
   ]
  },
  {
   "title": "Subscription count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "broker_subscriptions_count" }
   ]
  },
  {
   "title": "Published messages",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(recorder_measurements_total[$__rate_interval])",
     "legendFormat": "measurements created/s (recorder)"
    },
    {
     "expr": "rate(proxy_publish_total[$__rate_interval])",
     "legendFormat": "messages published/s (proxy)"
    }
   ]
  },
  {
   "title": "Other",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rules Loaded",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rule_rules_total", "legendFormat": "Rules" }
   ]
  },
  {
   "title": "Rule Triggers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "increase(rule_triggers_total[$__interval])",
     "legendFormat": "triggers"
    }
   ]
  }
 ]
}