FROM grafana/grafana:10.4.5

COPY grafana/dashboards/ /etc/grafana/provisioning/dashboards
COPY grafana/datasources/ /etc/grafana/provisioning/datasources
COPY grafana/notifiers/ /etc/grafana/provisioning/notifiers
