<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="prgRWEffIO" Id="{02288258-8b1d-4dbd-8ad3-1a1bf94c5849}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM prgRWEffIO
VAR
	fbRW1		: FB_ReadWrite_v2;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
fbRW1(
	eUploadType:= 4 ,	// every 1 minutes + change 
	bBusy=> , 
	bError=> , 
	udiErrorCodeOut=> , 
	eErrorReadWrite_Out=> );]]></ST>
    </Implementation>
    <LineIds Name="prgRWEffIO">
      <LineId Id="11" Count="5" />
      <LineId Id="10" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>