<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="prgRWEffIO" Id="{801d6275-c66c-4367-a89c-3ba3295f154b}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM prgRWEffIO
VAR
	fbRW1		: FB_ReadWrite_V2;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbRW1(
	eUploadType:= eSelectDataUploadType.e_Change_Intervall5min, 
	bBusy=> , 
	bError=> , 
	udiErrorCodeOut=> , 
	eErrorReadWrite_Out=> );]]></ST>
    </Implementation>
    <LineIds Name="prgRWEffIO">
      <LineId Id="10" Count="4" />
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>