<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="prgEMS" Id="{f24d5ef6-444b-41eb-99fd-5d978158793e}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM prgEMS
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="prgEMS">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>