export const defaultMappings = {
  SSP: {
    InputBattery_actualValue: "prgBattery.lrPowerBattery",
    InputOutside_actualValue: "prgEM.lrPowerEM1",
    InputPV_actualValue: "prgPV.lrPowerPV",
    Output16A_actualValue: "prgEM.lrPowerEM4",
    Output16A_off: "prgEMS.bQ3Off",
    Output16A_on: "prgEMS.bQ3On",
    Output16A_state: "prgEMS.bQ3State_NOT",
    Output32A1_actualValue: "prgEM.lrPowerEM2",
    Output32A1_off: "prgEMS.bQ1Off",
    Output32A1_on: "prgEMS.bQ1On",
    Output32A1_state: "prgEMS.bQ1State_NOT",
    Output32A2_actualValue: "prgEM.lrPowerEM3",
    Output32A2_off: "prgEMS.bQ2Off",
    Output32A2_on: "prgEMS.bQ2On",
    Output32A2_state: "prgEMS.bQ2State_NOT",
    OutputECharger_actualValue: "prgCS.lrPowerCS",
    OutputECharger_off: "prgEMS.bQ4Off",
    OutputECharger_on: "prgEMS.bQ4On",
    OutputECharger_state: "prgEMS.bQ4State_NOT",
    OutputSchuko_actualValue: "prgCalc.lrPowerQ56",
  },
};
