import { vueRouter } from "storybook-vue3-router";

import ChartTimetableConsumerComponent from "./ChartTimetableConsumer.vue";

export default {
  title: "Devices/MPC/EMS/ChartTimetableConsumer",
  component: ChartTimetableConsumerComponent,
};

const Template = {
  decorators: [vueRouter()],
};

export const ChartTimetableConsumer = {
  ...Template,
  args: {
    isPreview: true,
    mpcId: "mpc",
    systemsMappings: {
      pv: {
        components: {
          pv1: {
            power: "pvPower",
            systemType: "pvSystem",
            title: "Title",
            interval: undefined,
            error: "",
          },
        },
        count: 1,
      },
      generator: {
        components: {
          generator1: {
            power: "generatorPower",
            state_generator: "generatorState",
            enable_soc: "generatorEnable",
            disable_soc: "generatorDisable",
            switch_enable: "generatorSwitchEnable",
            state_enable: "generatorStateEnable",
            switch_reset: "generatorSwitchReset",
            state_reset: "generatorStateReset",
            systemType: "generator",
            title: "Title",
            interval: undefined,
            error: "",
          },
        },
        count: 1,
      },
      grid: {
        components: {
          grid1: {
            power: "gridPower",
            size: "gridSize",
            systemType: "grid",
            title: "Title",
            interval: undefined,
            error: "",
          },
        },
        count: 1,
      },
      battery: {
        components: {
          battery1: {
            power: "batteryPower",
            systemType: "battery",
            switch_enable: "batterySwitchEnable",
            state_enable: "batteryStateEnable",
            switch_reset: "batterySwitchReset",
            state_reset: "batteryStateReset",
            soc: "batterySoc",
            capacity: "batteryCapacity",
            target_power: "batteryTargetPower",
            priority: "batteryPriority",
            size_capacity: "batterySizeCapacity",
            title: "Title",
            interval: undefined,
            error: "",
          },
        },
        count: 1,
      },
      house: {
        components: {
          house1: {
            power: "housePower",
            systemType: "house",
            switch_enable: "houseSwitchEnable",
            state_enable: "houseStateEnable",
            title: "Title",
            interval: undefined,
            error: "",
          },
        },
        count: 1,
      },
      charge_station: {
        components: {
          charge_station1: {
            power: "chargeStationPower",
            error: "",
            title: "chargeStationTitle",
            car_connected: "chargeStationCarConnected",
            charging_time: "chargeStationChargingTime",
            state_charging_station: "chargeStationStateChargingStation",
            state_emergency: "chargeStationStateEmergency",
            state_manual: "chargeStationStateManual",
            min_power: "chargeStationMin",
            switch_emergency: "chargeStationSwitch",
            priority: "chargeStationPriority",
            enable_soc: "chargeStationEnable",
            disable_soc: "chargeStationDisable",
            max_power: "chargeStationMax",
            slider_manual: "chargeStationSliderManual",
            slider_target_power: "chargeStationTargetPower",
            slider_min_power: "chargeStationSliderMin",
            target_power: "chargeStationTargetPower",
            state_enable: "chargeStationStateEnable",
            switch_enable: "chargeStationSwitchEnable",
            switch_manual: "chargeStationSwitchManual",
            systemType: "charge_station",
          },
        },
        count: 1,
      },
      electric_heating: {
        components: {
          electric_heating1: {
            power: "electricHeatingPower",
            systemType: "electric_heating",
            temperature: "electricHeatingTemperature",
            target_power: "electricHeatingTargetPower",
            state_electric_heating: "electricHeatingState",
            switch_manual: "electricHeatingSwitchManual",
            state_manual: "electricHeatingStateManual",
            switch_emergency: "electricHeatingSwitchEmergency",
            state_time: "electricHeatingStateEmergency",
            switch_disable_protection: "electricHeatingSwitchDisable",
            state_disable_protection: "electricHeatingStateDisable",
            switch_enable: "electricHeatingSwitchEnable",
            state_enable: "electricHeatingStateEnable",
            slider_target_power: "electricHeatingSliderTargetPower",
            slider_manual: "electricHeatingSlider",
            max_power: {
              heating: "electricHeatingMaxPower",
            },
            hour_on: "electricHeatingHourOn",
            minute_on: "electricHeatingMinuteOn",
            hour_off: "electricHeatingHourOff",
            minute_off: "electricHeatingMinuteOff",
            target_temp_on: "electricHeatingTempOn",
            target_temp_off: "electricHeatingTempOff",
            target_temp_max: "electricHeatingTempMax",
            enable_soc: "electricHeatingEnable",
            disable_soc: "electricHeatingDisable",
            priority: "electricHeatingPriority",
            title: "Title",
            interval: undefined,
            error: "",
          },
        },
        count: 1,
      },
      heating_pump: {
        components: {
          heating_pump1: {
            power: "heatingPumpPower",
            systemType: "heating_pump",
            flow_temperature: "heatingPumpFlow",
            return_temperature: "heatingPumpReturn",
            inlet_temperature: "heatingPumpInlet",
            outlet_temperature: "heatingPumpOutlet",
            boiler_temperature: "heatingPumpBoiler",
            boiler_water_temperature: "heatingPumpBoilerWater",
            target_power: "heatingPumpTargetPower",
            state_heating_pump: "heatingPumpState",
            switch_manual: "heatingPumpSwitchManual",
            state_manual: "heatingPumpStateManual",
            switch_emergency: "heatingPumpSwitchEmergency",
            state_emergency: "heatingPumpStateEmergency",
            switch_time: "heatingPumpSwitchTime",
            state_time: "heatingPumpStateTime",
            switch_enable: "heatingPumpSwitchEnable",
            state_enable: "heatingPumpStateEnable",
            switch_reset: "heatingPumpSwichReset",
            state_reset: "heatingPumpStateReset",
            manual_power: "heatingPumpManualPower",
            slider_manual: "heatingPumpSliderManual",
            state_time_power: "heatingPumpStateTimePower",
            slider_power: "heatingPumpSliderPower",
            max_power: {
              heating: "heatingPumpMaxPower",
            },
            hour_on: "heatingPumpHourOn",
            minute_on: "heatingPumpMinuteOn",
            hour_off: "heatingPumpHourOff",
            minute_off: "heatingPumpMinuteOff",
            priority: "heatingPumpPririty",
            enable_soc: "heatingPumpEnable",
            disable_soc: "heatingPumpDisable",
            title: "Title",
            interval: undefined,
            error: "",
          },
        },
        count: 1,
      },
      big_consumer: {
        components: {
          big_consumer1: {
            power: "bigConsumerPower",
            systemType: "big_consumer",
            switch_manual: "bigConsumerSwitchManual",
            state_manual: "bigConsumerStateManual",
            switch_emergency: "bigConsumerSwitchEmergency",
            state_emergency: "bigConsumerStateEmergency",
            switch_enable: "bigConsumerSwitchEnable",
            state_enable: "bigConsumerStateEnable",
            slider_target_power: "bigConsumerSliderTarget",
            slider_manual: "bigConsumerSliderManual",
            target_power: "bigConsumerTargetPower",
            state_consumer: "bigConsumerStateConsumer",
            priority: "bigConsumerPriority",
            enable_soc: "bigConsumerEnableSoc",
            disable_soc: "bigConsumerDisableSoc",
            max_power: "bigConsumerMax",
            title: "Title",
            interval: undefined,
            error: "",
          },
        },
        count: 1,
      },
      state_enable_ems: "emsStateEnable",
      enable_ems: "emsEnable",
      operation_mode: "emsOperation",
      message: "emsMessage",
      size_main_fuse: "emsSize",
      max_depth: "emsMax",
      reserve_battery: "emsReserve",
      min_charge_battery: "emsMin",
      reserve_charge: "emsReserveCharge",
      update_time: "emsUpdate",
      allow_charging_button: "emsAllowButton",
      allow_charging_state: "emsAllowState",
      activate_main_fuse: "emsActivate",
      state_main_fuse: "emsStateMain",
    },
  },
};
