<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="prgPerData" Id="{99777527-37bb-4f53-af68-43827fbda431}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM prgPerData
VAR
	fbPerData			: FB_WritePersistentData_CX81xx;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbPerData(
	eSaveModeData:= eUSVSaveMode.eSaveWhenPowerfail, 
	bLoadPersistentDataOk=> , 
	bPowerFailDetect=> , 
	bError=> , 
	bySaveProcess=> , 
	dwStorageLast24h=> , 
	udiErrorCode=> );]]></ST>
    </Implementation>
    <LineIds Name="prgPerData">
      <LineId Id="7" Count="6" />
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>