<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="prgRWLynus" Id="{62995b61-8431-4bff-affc-05b4805b57ee}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM prgRWLynus
VAR
	fbRW1		: FB_ReadWrite;
	fbRW2		: FB_ReadWrite;
	fbRW3		: FB_ReadWrite;
	fbRW4		: FB_ReadWrite;
	fbRW5		: FB_ReadWrite;
	fbRW6		: FB_ReadWrite;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbRW1();
fbRW2();
fbRW3();
fbRW4();
fbRW5();
fbRW6();
]]></ST>
    </Implementation>
    <LineIds Name="prgRWLynus">
      <LineId Id="5" Count="0" />
      <LineId Id="12" Count="1" />
      <LineId Id="16" Count="0" />
      <LineId Id="18" Count="0" />
      <LineId Id="28" Count="0" />
      <LineId Id="17" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>