<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="prgPD" Id="{8370b593-b9d2-4c0b-8b25-a99511c8c6db}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM prgPD
VAR
	fbPers						: FB_WritePersistentData_CX81xx;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbPers(
	eSaveModeData:= eUSVSaveMode.eSaveWhenPowerfail, 
	bLoadPersistentDataOk=> , 
	bPowerFailDetect=> , 
	bError=> , 
	bySaveProcess=> , 
	dwStorageLast24h=> , 
	udiErrorCode=> );]]></ST>
    </Implementation>
    <LineIds Name="prgPD">
      <LineId Id="7" Count="6" />
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>