<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="prgRWLynus" Id="{aff76794-a195-49b5-a617-4aeaae11f21d}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM prgRWLynus
VAR
	fbRW1		: FB_ReadWrite_V2;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[

fbRW1(
	eUploadType:= 2 , 
	bBusy=> , 
	bError=> , 
	udiErrorCodeOut=> , 
	eErrorReadWrite_Out=> );]]></ST>
    </Implementation>
    <LineIds Name="prgRWLynus">
      <LineId Id="17" Count="0" />
      <LineId Id="11" Count="0" />
      <LineId Id="19" Count="4" />
      <LineId Id="10" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>