<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="FB_K_Bus_State_old" Id="{68776db2-618f-4e61-ad2a-697943a84fea}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_K_Bus_State_old
VAR_INPUT
END_VAR
VAR_OUTPUT
	uiKBusState_OUT					AT%I*		: UINT;											//K-Bus State from the Basestation on wich the Terminal KL6301 is connected
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//Creator : Kai Ebensperger
//Company : Lynus AG
//Date : 24.07.2021
//Version : 1.0.0.0

//With this Function Block its possible to connect the Variable on the output to the State Variable with the K-Bus Box
//In this Function we dont need code

]]></ST>
    </Implementation>
    <LineIds Name="FB_K_Bus_State_old">
      <LineId Id="26" Count="6" />
      <LineId Id="16" Count="0" />
      <LineId Id="25" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>