name: reusable teams success notification step

inputs:
  notification-uri:
    description: 'MS Teams Webhook URI'
    required: true

runs:
  using: 'composite'
  steps:
    - uses: jdcargile/ms-teams-notification@v1.4
      with:
        github-token: ${{ github.token }} # this will use the runner's token.
        ms-teams-webhook-uri: ${{ inputs.notification-uri }}
        notification-summary: "\U0001F680 SUCCESS deploying >>${{ env.IMAGE_NAME }}<< to >>${{ github.event.inputs.cluster }}-cluster<<. (branch: ${{ github.ref }})"
        notification-color: 04b306
        timezone: Europe/Vienna
        verbose-logging: false