name: connectivity_ci_cd

on:
  push:
    branches:
      - main
    paths:
      - "api/**"
      - "connectivity/**"
  pull_request:
    types: [review_requested, ready_for_review]
    branches:
      - main
    paths:
      - "api/**"
      - "connectivity/**"
  workflow_dispatch:
    inputs:
      cluster:
        description: "kubernetes cluster to deploy to"
        required: true
        default: "wec"
        type: choice
        options:
          - all
          - eneries
          - peneder
          - wec

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: connectivity

jobs:
  build:
    permissions:
        contents: read
        packages: write
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          python3 scripts/build_and_push.py --registry "${{ env.REGISTRY }}" --user "${{ github.actor }}" --password "${{ secrets.GITHUB_TOKEN }}" --repository "${{ github.repository }}" --image "${{ env.IMAGE_NAME }}" --sha "${{ github.sha }}" --context_path "." --dockerfile_path "${{ env.IMAGE_NAME }}/Dockerfile"
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - id: string
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.event.inputs.cluster }}
      - uses: eneries/keepass2env@v1
        with:
          keepass-file-path: "keepass/secrets.kdbx"
          keepass-master-password: ${{ secrets.KEEPASS_MASTER_PASSWORD }}
          keepass-group-filter: "cloud"
      - name: Deploy
        run: |
          python3 scripts/deploy_and_restart.py --cluster "${{ steps.string.outputs.lowercase }}" --deployment_file "${{ env.IMAGE_NAME }}/deployment.yaml" --replace_tag --sha "${{ github.sha }}" --resource_name "connectivity" --namespace_name "lynus" --restart_mode "rolling" --apply_only_on_changes
      
